export type Commodity = "Silver" | "Uranium" | "Copper" | "Gold" | "Coal";

export type DevelopmentStage = "Producer" | "Developer";

export type JurisdictionRisk = "Low" | "Medium" | "High";

export type CommodityPrice = {
  commodity: Commodity;
  price: number;
  unit: string;
  changePercent: number;
};

export type Company = {
  slug: string;
  company: string;
  ticker: string;
  exchange: string;
  commodity: Commodity;
  country: string;
  jurisdiction: string;
  jurisdictionRisk: JurisdictionRisk;
  stage: DevelopmentStage;
  marketCap: number;
  enterpriseValue: number;
  revenue: number;
  ebitda: number;
  evEbitda: number | null;
  fcfYield: number | null;
  netDebt: number;
  cash: number;
  production: number;
  productionUnit: string;
  aisc: number | null;
  aiscUnit: string;
  reserveLife: number;
  insiderOwnership: number;
  dividendYield: number;
  bullCase: string[];
  bearCase: string[];
  keyCatalysts: string[];
  riskFlags: string[];
};

export const commodities: Commodity[] = ["Silver", "Uranium", "Copper", "Gold", "Coal"];

export const commodityPrices: CommodityPrice[] = [
  { commodity: "Silver", price: 29.42, unit: "USD/oz", changePercent: 1.8 },
  { commodity: "Uranium", price: 86.25, unit: "USD/lb U3O8", changePercent: 0.6 },
  { commodity: "Copper", price: 4.52, unit: "USD/lb", changePercent: -0.4 },
  { commodity: "Gold", price: 2345, unit: "USD/oz", changePercent: 0.9 },
  { commodity: "Coal", price: 138, unit: "USD/t Newcastle", changePercent: -1.1 }
];

// Temporary sample universe. Replace this module with API adapters for market data,
// financial statements, reserves, ownership, and operating metrics when providers are connected.
export const companies: Company[] = [
  {
    slug: "pan-american-silver",
    company: "Pan American Silver",
    ticker: "PAAS",
    exchange: "NYSE",
    commodity: "Silver",
    country: "Canada",
    jurisdiction: "Americas",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 7400,
    enterpriseValue: 8100,
    revenue: 2300,
    ebitda: 1040,
    evEbitda: 7.8,
    fcfYield: 4.6,
    netDebt: 690,
    cash: 520,
    production: 21.1,
    productionUnit: "Moz AgEq",
    aisc: 17.8,
    aiscUnit: "USD/oz AgEq",
    reserveLife: 10,
    insiderOwnership: 1.3,
    dividendYield: 1.1,
    bullCase: ["Diversified Americas mine base", "Silver leverage with meaningful gold by-product cash flow"],
    bearCase: ["Peru and Mexico permitting remain uneven", "Margin sensitivity if silver retreats below cost curve"],
    keyCatalysts: ["La Colorada throughput recovery", "Escobal restart optionality", "Quarterly cost guidance update"],
    riskFlags: ["Multi-country permitting exposure", "Moderate net debt"]
  },
  {
    slug: "first-majestic-silver",
    company: "First Majestic Silver",
    ticker: "AG",
    exchange: "NYSE",
    commodity: "Silver",
    country: "Canada",
    jurisdiction: "Mexico / US",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 1600,
    enterpriseValue: 2050,
    revenue: 610,
    ebitda: 218,
    evEbitda: 9.4,
    fcfYield: 1.8,
    netDebt: 450,
    cash: 220,
    production: 26.9,
    productionUnit: "Moz AgEq",
    aisc: 19.7,
    aiscUnit: "USD/oz AgEq",
    reserveLife: 7,
    insiderOwnership: 2.4,
    dividendYield: 0,
    bullCase: ["High beta silver torque", "Meaningful operating leverage if San Dimas grades improve"],
    bearCase: ["Elevated AISC versus larger peers", "Narrow free cash flow cushion"],
    keyCatalysts: ["Jerritt Canyon restart plan", "San Dimas reserve update", "Mexican tax dispute progress"],
    riskFlags: ["High unit costs", "Thin FCF yield"]
  },
  {
    slug: "endeavour-silver",
    company: "Endeavour Silver",
    ticker: "EXK",
    exchange: "NYSE",
    commodity: "Silver",
    country: "Canada",
    jurisdiction: "Mexico",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 620,
    enterpriseValue: 710,
    revenue: 220,
    ebitda: 85,
    evEbitda: 8.4,
    fcfYield: -2.5,
    netDebt: 90,
    cash: 96,
    production: 8.6,
    productionUnit: "Moz AgEq",
    aisc: 21.5,
    aiscUnit: "USD/oz AgEq",
    reserveLife: 6,
    insiderOwnership: 3.1,
    dividendYield: 0,
    bullCase: ["Terronera can reset the cost base", "Strong silver beta in a small-cap vehicle"],
    bearCase: ["Construction execution risk", "Negative current free cash flow"],
    keyCatalysts: ["Terronera ramp milestones", "Debt package drawdown update", "Reserve replacement report"],
    riskFlags: ["Developer-style funding risk", "High AISC"]
  },
  {
    slug: "cameco",
    company: "Cameco",
    ticker: "CCJ",
    exchange: "NYSE",
    commodity: "Uranium",
    country: "Canada",
    jurisdiction: "Canada / Kazakhstan",
    jurisdictionRisk: "Low",
    stage: "Producer",
    marketCap: 22800,
    enterpriseValue: 23700,
    revenue: 2600,
    ebitda: 1270,
    evEbitda: 18.6,
    fcfYield: 2.2,
    netDebt: 900,
    cash: 1150,
    production: 17.6,
    productionUnit: "Mlb U3O8",
    aisc: 42,
    aiscUnit: "USD/lb U3O8",
    reserveLife: 18,
    insiderOwnership: 0.4,
    dividendYield: 0.2,
    bullCase: ["Tier-one contracting book", "Scarce large liquid uranium producer"],
    bearCase: ["Premium multiple embeds strong term-price expectations", "Kazakhstan JV supply can be disrupted"],
    keyCatalysts: ["Long-term contracting disclosures", "McArthur River output update", "Westinghouse contribution"],
    riskFlags: ["Premium EV/EBITDA", "Geopolitical JV exposure"]
  },
  {
    slug: "nexgen-energy",
    company: "NexGen Energy",
    ticker: "NXE",
    exchange: "NYSE",
    commodity: "Uranium",
    country: "Canada",
    jurisdiction: "Saskatchewan",
    jurisdictionRisk: "Low",
    stage: "Developer",
    marketCap: 4100,
    enterpriseValue: 3850,
    revenue: 0,
    ebitda: -55,
    evEbitda: null,
    fcfYield: null,
    netDebt: -250,
    cash: 250,
    production: 0,
    productionUnit: "Mlb U3O8",
    aisc: 24,
    aiscUnit: "USD/lb U3O8 LOM",
    reserveLife: 29,
    insiderOwnership: 3.8,
    dividendYield: 0,
    bullCase: ["Arrow is one of the highest-grade undeveloped uranium projects", "Net cash balance improves financing flexibility"],
    bearCase: ["No current cash flow", "Permitting and build schedule define valuation"],
    keyCatalysts: ["Federal environmental approval", "Project financing package", "Final investment decision"],
    riskFlags: ["Pre-revenue", "Permitting timeline risk"]
  },
  {
    slug: "denison-mines",
    company: "Denison Mines",
    ticker: "DNN",
    exchange: "NYSE American",
    commodity: "Uranium",
    country: "Canada",
    jurisdiction: "Saskatchewan",
    jurisdictionRisk: "Low",
    stage: "Developer",
    marketCap: 1800,
    enterpriseValue: 1600,
    revenue: 14,
    ebitda: -18,
    evEbitda: null,
    fcfYield: null,
    netDebt: -200,
    cash: 200,
    production: 0,
    productionUnit: "Mlb U3O8",
    aisc: 32,
    aiscUnit: "USD/lb U3O8 LOM",
    reserveLife: 22,
    insiderOwnership: 1.7,
    dividendYield: 0,
    bullCase: ["ISR plan could create a low-capex Athabasca producer", "Strong treasury for a developer"],
    bearCase: ["Technical execution risk for Wheeler River ISR", "Valuation depends on future uranium curve"],
    keyCatalysts: ["Phoenix feasibility update", "Permitting decision", "Offtake discussions"],
    riskFlags: ["Pre-production", "Negative EBITDA"]
  },
  {
    slug: "freeport-mcmoran",
    company: "Freeport-McMoRan",
    ticker: "FCX",
    exchange: "NYSE",
    commodity: "Copper",
    country: "United States",
    jurisdiction: "US / Indonesia / Peru",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 70200,
    enterpriseValue: 78500,
    revenue: 24800,
    ebitda: 8820,
    evEbitda: 8.9,
    fcfYield: 3.7,
    netDebt: 8300,
    cash: 4600,
    production: 4.2,
    productionUnit: "Blb Cu",
    aisc: 1.78,
    aiscUnit: "USD/lb Cu",
    reserveLife: 25,
    insiderOwnership: 1.1,
    dividendYield: 1.4,
    bullCase: ["Scale and liquidity make it core copper exposure", "Grasberg underground drives long reserve life"],
    bearCase: ["Indonesia policy risk can affect cash flow timing", "Large-cap multiple limits re-rating"],
    keyCatalysts: ["Grasberg smelter ramp", "US leach recovery project", "Copper price breakout"],
    riskFlags: ["Indonesia policy exposure", "Cyclical copper beta"]
  },
  {
    slug: "ivanhoe-mines",
    company: "Ivanhoe Mines",
    ticker: "IVN.TO",
    exchange: "TSX",
    commodity: "Copper",
    country: "Canada",
    jurisdiction: "DRC / South Africa",
    jurisdictionRisk: "High",
    stage: "Producer",
    marketCap: 17900,
    enterpriseValue: 19500,
    revenue: 2950,
    ebitda: 1740,
    evEbitda: 11.2,
    fcfYield: 2.9,
    netDebt: 1600,
    cash: 740,
    production: 0.42,
    productionUnit: "Mt Cu",
    aisc: 1.45,
    aiscUnit: "USD/lb Cu",
    reserveLife: 30,
    insiderOwnership: 13.6,
    dividendYield: 0,
    bullCase: ["Kamoa-Kakula is a world-class high-grade copper system", "Insider alignment is unusually strong"],
    bearCase: ["DRC jurisdiction discount can persist", "Growth capex absorbs free cash flow"],
    keyCatalysts: ["Phase 3 concentrator performance", "Western Foreland drilling", "Kipushi zinc ramp"],
    riskFlags: ["High jurisdiction risk", "Growth capex intensity"]
  },
  {
    slug: "southern-copper",
    company: "Southern Copper",
    ticker: "SCCO",
    exchange: "NYSE",
    commodity: "Copper",
    country: "United States",
    jurisdiction: "Peru / Mexico",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 81500,
    enterpriseValue: 87000,
    revenue: 10700,
    ebitda: 6100,
    evEbitda: 14.3,
    fcfYield: 2.1,
    netDebt: 5500,
    cash: 2500,
    production: 2.0,
    productionUnit: "Blb Cu",
    aisc: 1.62,
    aiscUnit: "USD/lb Cu",
    reserveLife: 37,
    insiderOwnership: 88.9,
    dividendYield: 3.1,
    bullCase: ["Very long reserve life", "Low-cost asset base with large dividend capacity"],
    bearCase: ["Premium valuation and concentrated control", "Permitting friction in Peru"],
    keyCatalysts: ["Tia Maria permitting", "Buenavista zinc ramp", "Dividend reset"],
    riskFlags: ["Premium valuation", "Governance concentration"]
  },
  {
    slug: "newmont",
    company: "Newmont",
    ticker: "NEM",
    exchange: "NYSE",
    commodity: "Gold",
    country: "United States",
    jurisdiction: "Global Tier 1",
    jurisdictionRisk: "Low",
    stage: "Producer",
    marketCap: 48500,
    enterpriseValue: 56000,
    revenue: 17500,
    ebitda: 7890,
    evEbitda: 7.1,
    fcfYield: 5.4,
    netDebt: 7500,
    cash: 3300,
    production: 6.9,
    productionUnit: "Moz AuEq",
    aisc: 1450,
    aiscUnit: "USD/oz Au",
    reserveLife: 15,
    insiderOwnership: 0.2,
    dividendYield: 2.3,
    bullCase: ["Largest gold reserve base in public equities", "Portfolio optimization can lift margins"],
    bearCase: ["Integration execution after major acquisition", "High absolute capex needs"],
    keyCatalysts: ["Non-core asset sales", "Synergy delivery", "Dividend framework update"],
    riskFlags: ["Integration complexity", "Higher leverage than peers"]
  },
  {
    slug: "agnico-eagle",
    company: "Agnico Eagle",
    ticker: "AEM",
    exchange: "NYSE",
    commodity: "Gold",
    country: "Canada",
    jurisdiction: "Canada / Finland / Mexico",
    jurisdictionRisk: "Low",
    stage: "Producer",
    marketCap: 34700,
    enterpriseValue: 36000,
    revenue: 6900,
    ebitda: 3500,
    evEbitda: 10.3,
    fcfYield: 3.9,
    netDebt: 1300,
    cash: 900,
    production: 3.4,
    productionUnit: "Moz Au",
    aisc: 1275,
    aiscUnit: "USD/oz Au",
    reserveLife: 14,
    insiderOwnership: 0.8,
    dividendYield: 2.1,
    bullCase: ["Best-in-class jurisdiction mix", "Consistent execution and reserve replacement"],
    bearCase: ["Quality premium caps near-term upside", "Lower beta than smaller producers"],
    keyCatalysts: ["Detour Lake expansion update", "Canadian Malartic underground ramp", "Exploration results"],
    riskFlags: ["Premium multiple"]
  },
  {
    slug: "barrick-gold",
    company: "Barrick Gold",
    ticker: "GOLD",
    exchange: "NYSE",
    commodity: "Gold",
    country: "Canada",
    jurisdiction: "Nevada / Africa / LatAm",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 30600,
    enterpriseValue: 32000,
    revenue: 11900,
    ebitda: 4630,
    evEbitda: 6.9,
    fcfYield: 6.2,
    netDebt: 1400,
    cash: 4100,
    production: 4.1,
    productionUnit: "Moz Au",
    aisc: 1360,
    aiscUnit: "USD/oz Au",
    reserveLife: 16,
    insiderOwnership: 0.7,
    dividendYield: 2.4,
    bullCase: ["Attractive valuation versus senior peers", "Copper growth adds strategic optionality"],
    bearCase: ["Higher jurisdiction mix risk", "Production growth has lagged market expectations"],
    keyCatalysts: ["Pueblo Viejo expansion", "Reko Diq project milestones", "Reserve update"],
    riskFlags: ["Emerging-market exposure", "Execution credibility"]
  },
  {
    slug: "peabody-energy",
    company: "Peabody Energy",
    ticker: "BTU",
    exchange: "NYSE",
    commodity: "Coal",
    country: "United States",
    jurisdiction: "US / Australia",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 2800,
    enterpriseValue: 2400,
    revenue: 4300,
    ebitda: 820,
    evEbitda: 2.9,
    fcfYield: 13.5,
    netDebt: -400,
    cash: 970,
    production: 126,
    productionUnit: "Mt coal",
    aisc: 84,
    aiscUnit: "USD/t",
    reserveLife: 18,
    insiderOwnership: 2.6,
    dividendYield: 1.5,
    bullCase: ["Net cash and strong buyback capacity", "Met coal optionality improves earnings mix"],
    bearCase: ["Thermal coal multiple structurally discounted", "Policy and ESG constraints limit buyer base"],
    keyCatalysts: ["Shoal Creek recovery", "Buyback pace", "Met coal pricing"],
    riskFlags: ["Commodity policy risk", "Thermal coal terminal value"]
  },
  {
    slug: "arch-resources",
    company: "Arch Resources",
    ticker: "ARCH",
    exchange: "NYSE",
    commodity: "Coal",
    country: "United States",
    jurisdiction: "United States",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 2900,
    enterpriseValue: 2600,
    revenue: 3100,
    ebitda: 720,
    evEbitda: 3.6,
    fcfYield: 11.1,
    netDebt: -300,
    cash: 410,
    production: 68,
    productionUnit: "Mt coal",
    aisc: 92,
    aiscUnit: "USD/t",
    reserveLife: 13,
    insiderOwnership: 1.9,
    dividendYield: 2.6,
    bullCase: ["Met coal focus supports higher quality cash flow", "Shareholder returns remain central"],
    bearCase: ["Cyclical pricing swings are severe", "Long-term demand uncertainty"],
    keyCatalysts: ["Leer South productivity", "Capital return authorization", "Export price realizations"],
    riskFlags: ["Coal demand risk", "High earnings cyclicality"]
  },
  {
    slug: "whitehaven-coal",
    company: "Whitehaven Coal",
    ticker: "WHC.AX",
    exchange: "ASX",
    commodity: "Coal",
    country: "Australia",
    jurisdiction: "New South Wales / Queensland",
    jurisdictionRisk: "Medium",
    stage: "Producer",
    marketCap: 5200,
    enterpriseValue: 6100,
    revenue: 5400,
    ebitda: 1680,
    evEbitda: 3.6,
    fcfYield: 8.8,
    netDebt: 900,
    cash: 840,
    production: 31,
    productionUnit: "Mt coal",
    aisc: 98,
    aiscUnit: "USD/t",
    reserveLife: 21,
    insiderOwnership: 0.9,
    dividendYield: 4.8,
    bullCase: ["Australian export assets provide pricing leverage", "Long reserve life supports dividends"],
    bearCase: ["Acquisition leverage reduced balance sheet flexibility", "Thermal coal discount remains structural"],
    keyCatalysts: ["BMA integration", "Debt paydown cadence", "Semi-soft coal price recovery"],
    riskFlags: ["Elevated net debt", "ESG discount"]
  }
];

export function getCompanyBySlug(slug: string) {
  return companies.find((company) => company.slug === slug);
}
